### ISSUE TITLE
Make dirbuf safer while it modifying filesystem 

### ISSUE THREAD

**Issue by RnYi** [elihunter173/dirbuf.nvim#21]
Dirbuf will apply all modifications immediately after I save the dirbuf buffer, which is dangerous.

So, I think Dirbuf should list all actions before applying them ( just like `:DirbufSync -dry-run`). After I confirm, Dirbuf can perform changings.

Or, some CLI tools list `trash`, `trash-cli` can be supported in Dirbuf, so that I can restore files deleted by accident.

**Comment by elihunter173** [comment]
I can see adding a `-confirm` option to `:DirbufSync` which lists out all actions like `:DirbufSync -dry-run`, then confirms that's what you want before doing the actual sync. Are you thinking you'd like it to always confirm actions when running `:write` or just specifically when you run `:DirbufSync -confirm`?

As for supporting other tools like `trash`, I'm not entirely opposed but that would require coming up with a good API for that, so I'll leave that for a future issue.

**Comment by RnYi** [comment]
> I can see adding a `-confirm` option to `:DirbufSync` which lists out all actions like `:DirbufSync -dry-run`, then confirms that's what you want before doing the actual sync. Are you thinking you'd like it to always confirm actions when running `:write` or just specifically when you run `:DirbufSync -confirm`?

I think it better to confirm whenever I running `:write`, so that I don't need to map a key to execute `:DirbufSync` (I have a keymap for `:write`). Maybe you can give an option for enabling this feature or not. 
And, how about decoupling `:DirbufSync` from `BufWrite` event, we can make current behavior as default one, but give another option to disable it, so some users can `:write` multitimes until he/she is satisfied, then execute `:DirbufSync`.

**Comment by elihunter173** [comment]
> I think it better to confirm whenever I running :write

This is what I thought, but I just wanted to make sure. I'll probably add a `write_options` configuration variable that allows you to configure what options get passed to `:DirbufSync` when you `:write` a dirbuf. In which case your configuration would look like
```lua
require("dirbuf").setup {
  write_options = "-confirm",
}
```

Please tell me if you think there is a better name for this variable.

>  And, how about decoupling `:DirbufSync` from `BufWrite` event, we can make current behavior as default one, but give another option to disable it, so some users can `:write` multitimes until he/she is satisfied, then execute `:DirbufSync`.

I don't quite understand what you mean here. A directory buffer is a purely in-memory buffer that isn't backed by a file so `:write`ing it doesn't actually do anything other than call `:DirbufSync` (see `buftype=acwrite`)

**Comment by RnYi** [comment]
> Please tell me if you think there is a better name for this variable.
> 
Emm, I'm always stocked in naming🤣, so I would say that's well enough.
 
> I don't quite understand what you mean here. A directory buffer is a purely in-memory buffer that isn't backed by a file so `:write`ing it doesn't actually do anything other than call `:DirbufSync` (see `buftype=acwrite`)
>
`:DirbufSync` will be executed after each `:write`, I mean that it would be better to add an option to disable this behavior. But I haven't read your source code, so maybe it's hard to implement it.

**Comment by elihunter173** [comment]
This has been implemented on `main`.

e3e20c3ebe42a1bee90b4d39a7024b1d0f083774 adds a `-confirm` option that prints out a list of actions like `-dry-run` and then asks for confirmation before running them.

7b9e5bb767f839174b4e6760fdfab891f71c56cb adds a `write_cmd` option (instead of `write_options`) which allows you to change the behavior of `:write` in a dirbuf.

If you want to make Dirbuf always ask for confirmation when running `:write`, you can use this config
```lua
require("dirbuf").setup {
  write_cmd = "DirbufSync -confirm",
}
```

If you want to completely disable `:write` in dirbufs like you mentioned, then you can use this config
```lua
require("dirbuf").setup {
  write_cmd = "", -- or "echoerr ':write disabled'" if you want an error message when you :write
}
```

> `:DirbufSync` will be executed after each `:write`, I mean that it would be better to add an option to disable this behavior. But I haven't read your source code, so maybe it's hard to implement it.

Luckily it wasn't too hard! :)

**Comment by luetage** [comment]
Currently dirbuf deletes a directory by looping through its content and deleting every file, afterwards deleting the directory itself. This is because only empty directories can be deleted. While the option to confirm changes is great, I’d still like the ability to use [trash-cli](https://github.com/andreafrancia/trash-cli). For anyone stumbling about this issue looking for a quick fix, it can be done by changing the rm function in `fs.lua` to this:

```lua
local function rm(path, ftype)
  local ok, err, _ = vim.fn.system("trash-put " .. path)
  if not ok then
    return err
  end
  return nil
end
```
