### ISSUE TITLE
[Question] Easiest way to move a file to another directory

### ISSUE THREAD

**Issue by zdcthomas** [elihunter173/dirbuf.nvim#31]
Hi! First off, I love the plugin, it's super fast and intuitive!
I was wondering what the easiest way to move a file to another directory is. I'm currently using [Dirvish](https://github.com/justinmk/vim-dirvish) which supports a file moving flow where a line is deleted and then the new directory is navigated to, and the file or files are pasted into the new directory.

I know that with dirbuf, a file can be renamed to include the path to the new directory and that will move it, but I was wondering if a flow similar to the one I described above was possible? 

Thanks!

**Comment by elihunter173** [comment]
Currently this kind of flow isn't possible, but it will be once I implement #7. This feature is actually my next goal for dirbuf.nvim and I have a semi-working prototype of it, but sadly I recently ran into a bit of a wall with it. However, I plan to continue working on it so hopefully this will be possible in the near-ish future.

Closing since #7 encompasses this.
