### ISSUE TITLE
Add up dir hotkeys

### ISSUE THREAD

**Issue by JoseConseco** [elihunter173/dirbuf.nvim#34]
Wold be great to have these by default:
```vim
nnoremap <buffer> <BS> <cmd>execute 'Dirbuf %:p'.repeat(':h', v:count1 + isdirectory(expand('%')))<CR>
nnoremap <buffer> <left> <cmd>execute 'Dirbuf %:p'.repeat(':h', v:count1 + isdirectory(expand('%')))<CR>
nnoremap <buffer> <right> <cmd>execute 'lua require"dirbuf".enter()'<CR>
```
This could be set by user in : 
~/.config/nvim/ftplugin/dirbuf.vim      -- mappings defined in  ftplugin/xyz.vim  file will only affect xyz  buffer type
But would be great to have them by default in

**Comment by elihunter173** [comment]
I'm closing this because I would prefer to keep the default keybindings in directory buffers as minimal as possible since I want them to be as close to just a normal text buffer as possible and this configuration is pretty small and reasonable to put into an `after/` ftplugin file or an autocmd. I make an exception for `-` and `<CR>` since they each are unique, not normally used for navigation, and are basically necessary to make dirbuf.nvim usable.

I also think this usecase is well served by the current `:h <Plug>` mappings to make it easy to change or add new mappings to dirbuf functionality. 

So for example, your usecase could become
```vim
nmap <buffer> <BS> <Plug>(dirbuf_up)
nmap <buffer> <left> <Plug>(dirbuf_up)
nmap <buffer> <right> <Plug>(dirbuf_enter)
```
which is a bit simpler.

Do note that these mapping disable the default mappings with the rationale that you're rebinding them only if you want to change the key rather than add a key. Dirvish does a similar thing, but I could see an argument for having to explicitly disable default mappings or make the documentation more clear
