### ISSUE TITLE
Feature: Ability to pass an `on_attach` function to set custom `dirbuf` buffer keymaps

### ISSUE THREAD

**Issue by sanka047** [elihunter173/dirbuf.nvim#38]
Instead of relying on autocmds, it would be nice to be able to setup custom keymaps using a hook that is always run once the `dirbuf` buffer is created. This is a nice-to-have and not completely necessary since we can use autocmds to do the same thing. Just curious if there would be interest in making this change.

**Comment by elihunter173** [comment]
I'm personally not interested in this change.

Since all directory buffers have their filetype set to `dirbuf`, imo it's cleaner and more understandable to use ftplugin files or FileType autocmds to do this kind of user-configuration. And since you can emulate the behavior of `on_attach` pretty easily, I'd rather avoid the extra configuration option.
```lua
vim.api.nvim_create_autocmd("FileType", {
  pattern = "dirbuf",
  callback = my_on_attach,
})
```

**Comment by sanka047** [comment]
That’s fair. I only mentioned since I figured it would be an easy change to make within the plugin since you already have an `ftplugin` that creates mappings where you could just toss in a call to the `hook` Without much change.
