### ISSUE TITLE
Allow setting of `bufhidden` to a different option

### ISSUE THREAD

**Issue by YorickPeterse** [elihunter173/dirbuf.nvim#8]
dirbuf currenty hardcodes `bufhidden` to `hide`: 

https://github.com/elihunter173/dirbuf.nvim/blob/a715e08725a9d18896c9532df34547a0bbebf5ca/lua/dirbuf.lua#L68

I personally prefer the approach dirvish takes where buffers are wiped when closing them. Unfortunately, due to the setting being hardcoded in dirbuf this is proving a challenge to set up. Would it be possible to allow customising this setting somehow?

**Comment by YorickPeterse** [comment]
A workaround would be something like this:

```vim
au BufWinEnter * lua if vim.bo.ft == 'dirbuf' then vim.bo.bufhidden = 'wipe' end
```

Using `BufReadPost` and the likes doesn't work, as it seems the mentioned setting is set after these events are triggered.

**Comment by elihunter173** [comment]
It's definitely technically possible. Is there a reason you prefer to have `bufhidden` set to wipe? I'm inclined to not add this as a configuration option because it seems to me like a source of potential bugs, although I don't see any right now, and the workaround doesn't seem too difficult.

Also, FWIW `BufReadPost` doesn't work because `dirbuf.edit_dirbuf()` is called on `BufEnter` which in turn runs `set_dirbuf_opts`. Since `BufEnter` is called after `BufReadPost`, any options you set on `BufReadPost` are overwritten. We call `dirbuf.edit_dirbuf()` on `BufEnter` to create and refresh the buffer automatically whenever you `:edit` or enter a dirbuf, which allows for easy reloading and prevents the dirbuf from drifting out of sync with the filesystem.

**Comment by YorickPeterse** [comment]
@elihunter173 Having `bufhidden=wipe` or similar means you don't end up with lots of dirbuf buffers piling up over time. Granted I don't use dirvish/dirbuf that often, it's nice not having it pile up. For similar reasons my dotfiles have a hook so that empty unnamed buffers get wiped when closing, so those don't pile either.

**Comment by elihunter173** [comment]
That makes sense. I'll play around with having `bufhidden=wipe` and see if that causes any issues. I don't plan to make it a configuration option because that seems pretty niche and I'd like to avoid configuration options for the reasons I mentioned above. But if it makes sense and doesn't cause any issues, I'll probably set `bufhidden=wipe`

**Comment by elihunter173** [comment]
One feature `bufhidden=wipe` might make easier is having `CTRL-^` work like it does in dirvish where you visit the last non-dirbuf buffer you had open. This idea was suggested in a [Reddit comment by u/llourenci](https://www.reddit.com/r/neovim/comments/s5puxc/comment/ht4ybqy/)

**Comment by elihunter173** [comment]
As of commit 7cdcd19324c93b90e7c2bf35e59680c174abac62, for all directory buffers `bufhidden=wipe`. So you should be able to remove your workaround @YorickPeterse 

Funnily enough, it seemed having `bufhidden=hide` was actually causing bugs with re-opening previously close directory buffers! So my fear of `bufhidden=wipe` causing bugs was wrong :)

**Comment by YorickPeterse** [comment]
@elihunter173 Thanks! :tada: :+1:
